name: Build Mejiro31 Firmware

permissions:
  contents: read

on:
  push:
    branches: [master, develop, xap]
  pull_request:
    paths:
      - "keyboards/jeebis/mejiro31/**"
      - "quantum/**"
      - "platforms/**"
      - "drivers/**"
      - "tmk_core/**"
      - "builddefs/**"
      - "lib/**"
      - "util/**"
      - "Makefile"
      - "requirements.txt"
      - ".github/workflows/ci_build_major_branch.yml"
      - ".github/workflows/ci_build_major_branch_keymap.yml"
  workflow_dispatch:

concurrency:
  group: mejiro31-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build jeebis/mejiro31:${{ matrix.keymap }}"
    strategy:
      fail-fast: false
      matrix:
        keymap:
          - jp_default
          - en_default
    uses: ./.github/workflows/ci_build_major_branch_keymap.yml
    with:
      keyboard: jeebis/mejiro31
      keymap: ${{ matrix.keymap }}
