name: Build QMK Keymap

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      keyboard:
        type: string
        required: true
      keymap:
        type: string
        required: true

jobs:
  build:
    name: "Compile ${{ inputs.keyboard }}:${{ inputs.keymap }}"
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:
      - name: Disable safe.directory check
        run: git config --global --add safe.directory "*"

      - name: Checkout firmware
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Compile firmware
        run: qmk compile -kb "${{ inputs.keyboard }}" -km "${{ inputs.keymap }}"

      - name: Upload firmware
        uses: actions/upload-artifact@v6
        with:
          name: firmware-${{ inputs.keymap }}
          if-no-files-found: error
          path: |
            *.bin
            *.hex
            *.uf2
